export { default as Nav } from './Nav'
export { default as Footer } from './Footer'
export { default as HomePage } from './Homepage'
export { default as Dashboard } from './Dashboard'
export { default as Menus } from './Menus'
export { default as Login } from './Login'
export { default as Register } from './Register'
export {default as Reset} from './Reset'